services:
  foundry:
    image: felddy/foundryvtt:latest
    volumes:
      - type: bind
        source: .data
        target: /data
    environment:
      - FOUNDRY_HOT_RELOAD=true
      - FOUNDRY_TELEMETRY=false
      - FOUNDRY_LANGUAGE=pt-BR.pt-BR
    env_file:
      - .env
    ports:
      - 30000:30000
